@startuml

+class Nodo {
    -nombre: String
    -tablaProbabilidad: Map<String,Double>
    +Nodo(nombre: String)
    +void vincularPredecesor(padre: Nodo)
    +void agregarProbabilidad(condicion: String, probabilidad: Double)
    +String getNombre()
    +List<Nodo> getPadres()
    +List<Nodo> getHijos()
    +Map<String, Double> getTablaProbabilidad()
    +Map<String, String> parseAsignaciones(condicion: String)
    +double probabilidadDada(asignacion: Map<String, String>)
}

+class RedBayesiana {
    -nodos: Map<String, Nodo>
    +RedBayesiana()
    +Nodo obtenerOCrearNodo(nombre: String)
    +Nodo obtenerNodo(nombre: String)
    +boolean contieneNodo(nombre: String)
    +void agregarDependencia(nombrePadre: String, nombreHijo: String)
    +Collection<Nodo> getNodos()
    +List<Nodo> getNodosEnOrdenTopologico()
    +Set<String> extraerDominio(nombreVariable: String)
    +Set<String> extraerDominio(nodo: Nodo)
}


Nodo "0..*" -- "0..*" Nodo : hijos
Nodo "0..*" -- "0..*" Nodo : padres
RedBayesiana o-- "0..*" Nodo : contiene

@enduml